### ISSUE TITLE
Examples may reference variables before they are defined

### ISSUE THREAD

**Issue by xecej4** [codee-com/open-catalog#27]
Some of the example Fortran codes reference undefined variables. For example, PWR063 attempts to print the whole array X(1:10) inside the DO I loop, although only X(1:I) are defined when the WRITE statement in the loop is executed. I suggest that the statement be changed from

`        write(*,*) "Update X =", X`

to

`        write(*,*) "Update X =", X(:I)`

**Comment by alvrogd** [comment]
Thank you for pointing out this error! We'll correct it and review other Fortran codes in the catalog for similar problems.

If you find any further issues, please feel free to open a pull request as well to amend them if you're interested. All contributions are highly valued :)

We'll keep the issue open and update it once the correction is made.

**Comment by alvrogd** [comment]
The PWR063 issue is now resolved in #29! Thank you once again for your feedback :)
